services:

  # send-test-tle:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.test
  #   container_name: prueba1
  #   networks:
  #     - kafka-net
  get-test-tle_from-api:
    build:
      context: .
      dockerfile: Dockerfile.get
    container_name: get-tle-from-api
    networks:
      - kafka-net

networks:
  kafka-net:
    external: true