# Configuración del módulo tle-pass-activity-generator
kafka:
  bootstrap_servers: kafka-broker-1:9092
  topic: _TLE
  group_id: tle-pass-activity-group
schema_registry:
  url: http://schema-registry:8081
