app:
  ack_check: false
  message_ack_timeout: 30 # Tiempo maximo de espera del mensaje ACK
  message_types: # Seteo de los nombres para los Tipos de Mensajes
    tle_type: "NEWPLANN"
    plan_type: "PLANN"
    plan_tle_type: "PLANTLE"
  min_hours_required: 1 # Horas minimas requeridas para la planificacion
  max_hours_required: 72 # Horas maximas requeridas para la planificacion
  min_hours_tle_required: 5 # Horas minimas requeridas para enviar sin el TLE
kafka:
  bootstrap_servers: "kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092"
  schema_registry_url: "http://schema-registry:8081"
  group_id: "sender-module"
  auto_offset_reset: "earliest" # / latest -> Si se quieren consultar todos o solamente los nuevos mensajes entrantes
  enable_auto_commit: false # Se realiza el commit manualmente al finalizar de procesar el mensaje
  topic:
    sender_topic: "PLANN"
    ack_topic: "ACK"
    event_topic: "EVENTS"
  schema:
    sender_plann: "/app/config/schema_plann.json"
    sender_plann_tle: "/app/config/schema_plann_tle.json"
  waiting_time: 30
  max_retries: 5
database:
  dbname: "planificacion_satelital"
  user: "planificador_app"
  password: "/app/password/db_pass"
  host: "satplan_db"
logs:
  folder: "logs"
  filename: "PostTLE.log"
  rotation: 5,
  size: 5000000
  log_level: "debug" # / info
mail:
  notifications: true
  mailserver: "200.16.81.74"
  from: "email-agent@conae.gov.ar"
  to: ["cgss.systemsupport@conae.gov.ar"]
  attachments: ""