services:
  viasat-direct:
    image: viasat-tle-sender:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viasat-tle-sender
    hostname: viasat-tle-sender_direct
    networks:
      - viasat-tle-sender_network
      - actualiza_tle_broker-kafka
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs
      - /home/iambrosino/viasat-tle-sender/test/passwd:/app/passwd
networks:
  viasat-tle-sender_network:
    driver: bridge
    ipam:
      config:
        - subnet: '172.29.0.0/16'
          gateway: '172.29.0.1'
  actualiza_tle_broker-kafka:
    external: true