version: '3'
x-proxy-env: &proxy-env
  http_proxy: http://cuss_sys:c5%24%24pr4xy@10.0.100.200:3128
  https_proxy: http://cuss_sys:c5%24%24pr4xy@10.0.100.200:3128
  no_proxy: localhost,127.0.0.1,10.0.0.0/8,schema-registry
services:
  viasat-tle-sender:
    image: cgss-harbor.et.conae.gov.ar/etc/viasat-tle-sender:0.2.1
    container_name: viasat-tle-sender
    hostname: viasat-tle-sender
    environment: *proxy-env
    networks:
      - kafka-net
    volumes:
      - /home/soporte/actualiza-tle/logs:/app/logs
      - /home/soporte/actualiza-tle/configs/viasat-tle-config:/app/configs
      - /home/soporte/actualiza-tle/password:/app/password
networks:
  kafka-net:
    external: true
