version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: satplan_db
    environment:
      POSTGRES_DB: planificacion_satelital
      POSTGRES_USER: planificador_app
      POSTGRES_PASSWORD: SecurePassword123!
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U planificador_app -d planificacion_satelital"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kafka-net
volumes:
  pgdata: 
  
networks:
  kafka-net:
    external: true