app:
  antenna_id: "ANTENA_DEFAULT"
  broadcast_tle: false
  tle_cache_days: 3
logs:
  log_level: "INFO"
files:
  tle_load_filename: "rciEphem_PLANNER_LOAD.txt"
  tle_status_filename: "importEphem_PLANNER_LOAD.txt"
  planning_load_filename: "rciSched_PLANNER_LOAD.txt"
  planning_status_filename: "importSched_PLANNER_LOAD.txt"
send:
  sleep_time: 60
  connection_method: "direct" # / tunnel / double_tunnel
